language: ruby
rvm:
  - 2.1
jdk:
  - oraclejdk8
before_script:
  - pip install --user html5validator
  - npm install a11y
#  - gem install html-proofer
script: ./script/cibuild
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  on:
    branch: master
