language: ruby
rvm:
- 2.1
before_script:
- pip install --user html5validator
- npm install git+https://github.com/strategicdata/a11y.git#feature-cli-exit-codes
script: ./script/cibuild
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  on:
    branch: master
