# Permalinks
permalink:           pretty

# Setup
title:               WebSurvey
url:                 http://www.websurvey.com.au

# About/contact
author:
  name:              'WebSurvey'
  email:             'info@websurvey.com.au'
  github:            'https://github.com/strategicdata/websurvey.com.au'

exclude: [node_modules,vendor,blog,_posts]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
