[
  {
	"Category":{"type": "string"},
	"Color":{"type": "string"},
	"D":{"type": "date", "caption": "Date"},
	"W":{"type": "weekday", "caption":"Week Day"},
	"Time":{"type": "time"},
	"Date Time":{"type": "datetime"},
	"country":{"type":"level", "hierarchy": "Geography", "level":"Country"},
	"state":{"type":"level", "hierarchy": "Geography", "level":"State", "parent": "Country"},
	"city":{"type":"level", "hierarchy": "Geography", "parent": "State"},
	"Price":0,
	"Quantity":{"type": "number"},
	"Discount":0
  },
  {
	"Category":"Accessories",
	"Color":"green",
	"D":"02/08/2014",
	"W":"Wed",
	"Time":"2000",
	"Date Time": 1437850374064,
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":174,
	"Quantity":22,
	"Discount":23
  },
  {
	"Category":"Accessories",
	"Color":"red",
	"D":"09/02/2015",
	"W":"Mon",
	"Time":"1000",
	"country" : "USA",
	"state" : "California",
	"city" : "Los Angeles",
	"Price":1664,
	"Quantity":19,
	"Discount":7
  },
  {
	"Category":"Bikes",
	"Color":"",
	"D":"01/08/2014",
	"W":"Mon",
	"Time":"1000",
	"Date Time": 1437850827958,
	"country" : "Canada",
	"state" : "Quebec",
	"city" : "Montreal",
	"Price":1190,
	"Quantity":292,
	"Discount":36
  },
  {
	"Category":"Clothing",
	"Color":"green",
	"D":"04/08/2015",
	"W":"Fri",
	"Time":"1000",
	"country" : "USA",
	"state" : "California",
	"city" : "Los Angeles",
	"Price":1222,
	"Quantity":730,
	"Discount":38
  },
  {
	"Category":"Cars",
	"Color":"white",
	"D":"01/01/2014",
	"W":"Wed",
	"Time":"1000",
	"country" : "USA",
	"state" : "California",
	"city" : "Los Angeles",
	"Price":7941,
	"Quantity":73,
	"Discount":53
  },
  {
	"Category":"Clothing",
	"Color":"",
	"D":"01/11/2015",
	"W":"Wed",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":6829,
	"Quantity":19,
	"Discount":56
  },
  {
	"Category":"Components",
	"Color":"green",
	"D":"01/10/2014",
	"W":"Wed",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Quebec",
	"city" : "Montreal",
	"Price":2995,
	"Quantity":98,
	"Discount":8.9
  },
  {
	"Category":"Components",
	"Color":"white",
	"D":"01/22/2015",
	"W":"Mon",
	"Time":"1000",
	"country" : "USA",
	"state" : "California",
	"city" : "Los Angeles",
	"Price":2471,
	"Quantity":93,
	"Discount":14
  },
  {
	"Category":"Components",
	"Color":"yellow",
	"D":"01/07/2015",
	"W":"Fri",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":6650,
	"Quantity":40,
	"Discount":4
  },
  {
	"Category":"Cars",
	"Color":"blue",
	"D":"01/08/2014",
	"W":"Wed",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":865,
	"Quantity":45,
	"Discount":7
  },
  {
	"Category":"Cars",
	"Color":"purple",
	"D":"01/08/2015",
	"W":"Wed",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Quebec",
	"city" : "Montreal",
	"Price":511,
	"Quantity":46,
	"Discount":20
  },
  {
	"Category":"Clothing",
	"Color":"blue",
	"D":"01/09/2015",
	"W":"Mon",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Quebec",
	"city" : "Montreal",
	"Price":981,
	"Quantity":18,
	"Discount":36
  },
  {
	"Category":"Accessories",
	"Color":"blue",
	"D":"02/09/2015",
	"W":"Wed",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":284,
	"Quantity":24,
	"Discount":42
  },
  {
	"Category":"Cars",
	"Color":"red",
	"D":"03/08/2015",
	"W":"Fri",
	"Time":"1000",
	"country" : "Canada",
	"state" : "Ontario",
	"city" : "Toronto",
	"Price":827,
	"Quantity":72,
	"Discount":26.1
  }
]