#!/usr/bin/env bash
set -e # halt script on error

if command -v ruby >/dev/null 2>&1 && command -v gem >/dev/null 2>&1; then
  RUBYPATH="$(ruby -rubygems -e 'puts Gem.user_dir')"
fi

if command -v python >/dev/null 2>&1; then
  PYTHONPATH="$(python -m site --user-base)"
fi

command -v $RUBYPATH/bin/jekyll >/dev/null 2>&1  \
  || gem install --user-install jekyll

command -v $RUBYPATH/bin/htmlproof >/dev/null 2>&1 \
  || gem install --user-install html-proofer

command -v $PYTHONPATH/bin/html5validator >/dev/null 2>&1 \
  || pip install --user html5validator

bundle exec $RUBYPATH/bin/jekyll build
$PYTHONPATH/bin/html5validator --root ./_site
bundle exec $RUBYPATH/bin/htmlproof ./_site --disable-external
(sleep 3; open http://127.0.0.1:4000) &
bundle exec jekyll serve
