#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
#bundle exec htmlproof ./_site --check-html --disable-external
html5validator --root ./_site
bundle exec htmlproof ./_site --disable-external
