#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
#bundle exec htmlproof ./_site --check-html --disable-external
$HOME/.local/bin/html5validator --root ./_site
bundle exec htmlproof ./_site --disable-external
./node_modules/a11y/cli.js {_site/*.html,_site/**/*.html} --fail-on-error

