#!/usr/bin/env bash
set -e # halt script on error

(sleep 15; open http://127.0.0.1:4000) &
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll bundle exec jekyll serve
